
permissions:
  checks: write
  contents: read
  
name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install
      
    - name: Publish test results
      if: always()  # Run even if previous step fails
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: target/surefire-reports/TEST-*.xml
